### ISSUE TITLE
Database formatting issue

### ISSUE THREAD

**Issue by francemartino** [meglecz/mkLTG#1]
Hi Emese,

First of all, thank you for your work on both mkLTG and mkCOInr, fantastic tools!

I am trying to use **mkLTG** for my eDNA dataset (**COI**) and would like to use the custom database I previously created with **mkCOInr**. However, following the mkCOInr tutorial, the output in VTAM format (compatible with mkLTG) includes only these files:

- blastdb_name.nhr
- blastdb_name.nin
- blastdb_name.nog
- blastdb_name.nsd
- blastdb_name.nsi
- blastdb_name.nsq

If you look at the "ready to use" database linked here on mkLTG, the number of files inside is larger:

├── COInr_for_vtam_2022_05_06_dbV5
├── COInr_for_vtam.**ndb**
├─── COInr_for_vtam.nhr
├─── COInr_for_vtam.nin
├─── COInr_for_vtam.nog
├─── COInr_for_vtam.**nos**
├─── COInr_for_vtam.**not**
├─── COInr_for_vtam.nsq
├─── COInr_for_vtam.**ntf**
├─── COInr_for_vtam.**nto**
├─── COInr_for_vtam_taxonomy.tsv
│ └─── format_db.log

Did I miss something or is there a way to use my custom database for mkLTG too? 
Thanks in advance for any help!

**Comment by meglecz** [comment]
Hi,

I am glad you like my tools. I think the difference comes from the BLAST version and the version of the BLAST database.
If you are using BLAST 2.9.0+ or higher, it will produce version 5 BLAST databases with more files, and if you are using an earlier version of BLAST, it will produce version 4 BLAST databases (https://ncbiinsights.ncbi.nlm.nih.gov/2019/05/24/have-you-tried-blast-2-9-0-and-version-5-blast-databases-dbv5/).

Both version 4 and version 5 databases should work with mkLTG, if you have the appropriate version of BLAST.
It seems to me that you used an older version of BLAST (before 2.9.0) when you have produced your custom database from COInr. Just keep using the same BLAST and mkLTG should work with your custom database.

If making custom databases from COInr, check for updates in zenodo (https://zenodo.org/records/7898363 ). I am making yearly updates. The last is from may 2023.

I hope it helps!
Emese

**Comment by francemartino** [comment]
It works! 

I was using a pretty old version of blast.
Thank you very much. I'm sorry for the stupid question.

I wish you a nice day

Francesco

**Comment by meglecz** [comment]
Great!
